language: php

php:
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
